[profile.default]
src = "contracts"
script = "scripts"
test = "tests"
out = "artifacts"
libs = ["node_modules"]
gas_reports = ["CommonAggregator"]
optimizer = true
optimizer-runs = 10_000
via-ir = true

remappings = [
    "forge-std/=node_modules/forge-std/src",
    "@openzeppelin/=node_modules/@openzeppelin/",
]

no_match_path = "tests/aggregator/UpgradesOpenZeppelin.t.sol"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
aleph_evm_testnet = "${ALEPH_EVM_TESTNET_RPC_URL}"

[doc]
ignore = [
    "contracts/Math.sol",
    "contracts/interfaces/Initialiators.sol",
]

# Includes also openzeppelin foundry upgrades
[profile.full]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "artifacts" }]
no_match_path = "../"

[profile.ci]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "artifacts" }]
no_match_path = "../"
